### ISSUE TITLE
use of simd is not quite correct

### ISSUE THREAD

**Issue by BurntSushi** [TooManyBees/lab#10]
Neat library! Unfortunately, I think the SIMD use here is not quite correct. Using the SIMD vendor intrinsics is not simple. You'll want to give a _very careful_ read of the [`std::arch` docs](https://doc.rust-lang.org/std/arch/index.html#overview), and specifically about what obligations to safety you have.

Just as a few examples:

* [`simd::labs_to_rgbs`](https://docs.rs/lab/0.7.0/lab/simd/fn.labs_to_rgbs.html#panics) says that it will panic if the necessary CPU support doesn't exist, but looking at the implementation, this doesn't seem to be true. As written, this function _must_ be marked `unsafe`, unless you do indeed fix the implementation to panic.
* You generally need to specify `target_feature` on functions that use SIMD vendor intrinsics. Note the docs for that here: https://doc.rust-lang.org/std/arch/index.html#dynamic-cpu-feature-detection
* It seems like your crate wants to rely on runtime CPU feature detection, but is mixing this up with providing addition SIMD platform specific APIs. I think _ideally_ you wouldn't have a SIMD module exposed at all. Your implementations should just do the right thing when SIMD is available.

As an example of how to do all of this, look at the `memchr` crate. It has no specific SIMD public APIs. It exposes no unsafe routines. It never panics. But it also uses SIMD when available, and falls back to slower implementations when not available.

**Comment by TooManyBees** [comment]
Addressed in current release
