### ISSUE TITLE
MaybeUninit::uninit().assume_init()

### ISSUE THREAD

**Issue by kornelski** [TooManyBees/lab#23]
`MaybeUninit::uninit().assume_init()` is an instant Undefined Behavior by definition. Unfortunately, mere *existence* of a reference to uninitialized memory is UB in Rust. You have to use raw pointers to fill in such arrays.

**Comment by mina86** [comment]
https://doc.rust-lang.org/std/mem/union.MaybeUninit.html#initializing-an-array-element-by-element seems to be contradicting your statement.

**Comment by kornelski** [comment]
Oh right. I see that it doesn't make initialized memory, it's just two levels of `MaybeUninit`. My bad.
